name: 'automatic-actions'
description: 'Get a new version tag for your next release.'
author: 'Soumeh'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TOKEN: ${{ inputs.token }}
    COMMITS: ${{ inputs.commits }}
    REPO: ${{ inputs.repo }}
inputs:
  token:
    description: GitHub Personal Access Token. (Auto Populated)
    default: ${{ github.token }}
  commits:
    description: A list of commits to check for changes in. (Auto Populated)
    default: ${{ github.event.commits }}
  repo:
    description: The repository to scan for the latest version in. (Auto Populated)
    default: ${{ github.repository }}
outputs:
  tag:
    description: The new version tag.
branding:
  icon:  'chevrons-up'
  color: 'gray-dark'