name: 'automatic-actions'
description: 'Get a new version tag for your next release.'
author: 'Soumeh'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TOKEN: ${{ inputs.token }}
    BEFORE: ${{ inputs.before }}
    AFTER: ${{ inputs.after }}
    REPO: ${{ inputs.repo }}
    FALLBACK_TAG: ${{ inputs.fallback_tag }}
inputs:
  fallback_tag:
    description: If no previous tag was found, use this one.
    default: 0.0.0
  token:
    description: GitHub Personal Access Token. (Auto Populated)
    default: ${{ github.token }}
  before:
    description: Which commit to start looking for changes in. (Auto Populated)
    default: ${{ toJSON(github.event.before) }}
  after:
    description: Which commit to end looking for changes in. (Auto Populated)
    default: ${{ toJSON(github.event.after) }}
  repo:
    description: The repository to scan for the latest version in. (Auto Populated)
    default: ${{ toJSON(github.repository) }}
outputs:
  tag:
    description: The new version tag.
  changelog:
    description: Multi-line string changelog.
branding:
  icon:  'chevrons-up'
  color: 'gray-dark'