name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Test
        uses: Soumeh/Auto-Versioning@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}