name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Test
        uses: Soumeh/build-resource-pack@master
        with:
          filename: TestPack
          items: |
            folder1
            folder2
          gen-sha1: true
      - name: Publish
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'build'
          force-add: 'true'
          commit-message: 'compile packs'
          name: Compiler[bot]
          email: my.github@email.com 